//! Turning stored entries into live shell definitions, wiring up rc files,
//! and importing a user's currently active aliases/functions.

use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Duration;

use anyhow::{Context, Result, bail};
use wait_timeout::ChildExt;

use crate::model::{Entry, Kind};
use crate::paths::{Paths, home_dir};

/// A supported interactive shell.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Shell {
    Zsh,
    Bash,
}

impl Shell {
    pub fn all() -> [Shell; 2] {
        [Shell::Zsh, Shell::Bash]
    }

    pub fn as_str(self) -> &'static str {
        match self {
            Shell::Zsh => "zsh",
            Shell::Bash => "bash",
        }
    }

    /// File name of the generated definitions file for this shell.
    pub fn filename(self) -> &'static str {
        match self {
            Shell::Zsh => "cmd-man.zsh",
            Shell::Bash => "cmd-man.bash",
        }
    }

    /// rc files (relative to home) that should source the generated file.
    ///
    /// For bash we consider both `.bashrc` and `.bash_profile` so both
    /// interactive and login shells pick up definitions.
    fn rc_relatives(self) -> &'static [&'static str] {
        match self {
            Shell::Zsh => &[".zshrc"],
            Shell::Bash => &[".bashrc", ".bash_profile"],
        }
    }
}

const BLOCK_START: &str = "# >>> cmd-man >>>";
const BLOCK_END: &str = "# <<< cmd-man <<<";

/// Render the generated definitions file for a shell.
pub fn render(shell: Shell, entries: &[Entry]) -> String {
    let mut sorted: Vec<&Entry> = entries.iter().collect();
    sorted.sort_by(|a, b| a.name.cmp(&b.name));

    let mut out = String::new();
    out.push_str("# Generated by cmd-man. Do not edit by hand.\n");
    out.push_str(&format!(
        "# Regenerate with: cmd-man reload ({})\n\n",
        shell.as_str()
    ));

    for entry in sorted {
        out.push_str(&render_entry(entry));
        out.push('\n');
    }
    out
}

fn render_entry(entry: &Entry) -> String {
    match entry.kind {
        Kind::Alias => format!("alias {}={}\n", entry.name, single_quote(&entry.command)),
        Kind::Function => {
            let body = entry.command.trim_end_matches('\n');
            format!("{}() {{\n{}\n}}\n", entry.name, body)
        }
    }
}

/// Quote a string for safe use inside single quotes in sh/zsh/bash.
fn single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// Regenerate the enabled shell definition files from the given entries.
pub fn regenerate(paths: &Paths, entries: &[Entry], zsh: bool, bash: bool) -> Result<()> {
    paths.ensure_dirs()?;
    if zsh {
        write_shell_file(paths, Shell::Zsh, entries)?;
    }
    if bash {
        write_shell_file(paths, Shell::Bash, entries)?;
    }
    Ok(())
}

fn write_shell_file(paths: &Paths, shell: Shell, entries: &[Entry]) -> Result<()> {
    let text = render(shell, entries);
    let file = paths.shell_file(shell);
    std::fs::write(&file, text).with_context(|| format!("writing {}", file.display()))?;
    Ok(())
}

/// Express a path using `$HOME` when it lives under the home directory, so the
/// rc block stays portable across machines.
fn portable_path(path: &Path) -> String {
    if let Some(home) = home_dir()
        && let Ok(rest) = path.strip_prefix(&home)
    {
        return format!("$HOME/{}", rest.display());
    }
    path.display().to_string()
}

/// The managed rc block that sources a generated shell file.
fn rc_block(shell_file: &Path) -> String {
    let p = portable_path(shell_file);
    format!(
        "{BLOCK_START}\n# Managed by cmd-man. Re-run `cmd-man init` to refresh.\n[ -f \"{p}\" ] && source \"{p}\"\n{BLOCK_END}\n"
    )
}

/// Insert or replace the managed block within an rc file's text. Idempotent.
pub fn upsert_block(existing: &str, block: &str) -> String {
    let lines: Vec<&str> = existing.lines().collect();
    let start = lines.iter().position(|l| l.trim() == BLOCK_START);
    let end = lines.iter().position(|l| l.trim() == BLOCK_END);

    // Keep only the lines outside a managed block. A well-formed, ordered pair
    // removes the whole region; a malformed/partial block has its stray marker
    // lines dropped so a single clean block can be re-inserted.
    let mut kept: Vec<&str> = match (start, end) {
        (Some(s), Some(e)) if e >= s => lines
            .iter()
            .enumerate()
            .filter(|(i, _)| *i < s || *i > e)
            .map(|(_, l)| *l)
            .collect(),
        _ => lines
            .iter()
            .filter(|l| l.trim() != BLOCK_START && l.trim() != BLOCK_END)
            .copied()
            .collect(),
    };
    // Drop trailing blank lines so repeated inserts stay idempotent.
    while kept.last().is_some_and(|l| l.trim().is_empty()) {
        kept.pop();
    }

    let mut out = kept.join("\n");
    if !out.is_empty() {
        out.push('\n');
        out.push('\n');
    }
    out.push_str(block);
    out
}

/// Files that were touched while installing rc blocks.
#[derive(Debug, Default)]
pub struct InitReport {
    pub touched: Vec<PathBuf>,
}

/// Install the managed source block into the rc files for enabled shells.
pub fn install_rc(paths: &Paths, zsh: bool, bash: bool) -> Result<InitReport> {
    let home = home_dir().context("could not determine home directory")?;
    let mut report = InitReport::default();
    let mut targets: Vec<Shell> = Vec::new();
    if zsh {
        targets.push(Shell::Zsh);
    }
    if bash {
        targets.push(Shell::Bash);
    }

    for shell in targets {
        let block = rc_block(&paths.shell_file(shell));
        let rc_files = rc_targets(&home, shell);
        for rc in rc_files {
            let existing = std::fs::read_to_string(&rc).unwrap_or_default();
            let updated = upsert_block(&existing, &block);
            if updated != existing {
                std::fs::write(&rc, updated)
                    .with_context(|| format!("writing {}", rc.display()))?;
                report.touched.push(rc);
            }
        }
    }
    Ok(report)
}

/// Choose which rc files to write for a shell: every existing candidate, or the
/// first candidate as a default when none exist yet.
fn rc_targets(home: &Path, shell: Shell) -> Vec<PathBuf> {
    let candidates: Vec<PathBuf> = shell.rc_relatives().iter().map(|r| home.join(r)).collect();
    let existing: Vec<PathBuf> = candidates.iter().filter(|p| p.exists()).cloned().collect();
    if existing.is_empty() {
        vec![candidates[0].clone()]
    } else {
        existing
    }
}

/// Parse the output of the shell `alias` builtin into (name, command) pairs.
pub fn parse_aliases(text: &str) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty() {
            continue;
        }
        // zsh/bash may prefix each line with "alias ".
        let line = line.strip_prefix("alias ").unwrap_or(line);
        let Some((name, value)) = line.split_once('=') else {
            continue;
        };
        let name = name.trim();
        if name.is_empty() {
            continue;
        }
        out.push((name.to_string(), unquote(value.trim())));
    }
    out
}

/// Strip one layer of surrounding single or double quotes and unescape `'\''`.
fn unquote(s: &str) -> String {
    let bytes = s.as_bytes();
    if bytes.len() >= 2
        && (bytes[0] == b'\'' || bytes[0] == b'"')
        && bytes[bytes.len() - 1] == bytes[0]
    {
        let inner = &s[1..s.len() - 1];
        return inner.replace("'\\''", "'");
    }
    s.to_string()
}

/// Collect the active aliases from an interactive shell process.
///
/// This spawns `<shell> -i -c 'alias'`, which sources the user's rc files, so
/// it is only run for the explicit `import` command and is timeboxed.
pub fn collect_active_aliases(shell: Shell) -> Result<Vec<(String, String)>> {
    let output = run_shell_snippet(shell, "alias", Duration::from_secs(10))?;
    Ok(parse_aliases(&output)
        .into_iter()
        .filter(|(name, _)| {
            is_importable_name(name) && !SHELL_INTERNAL_ALIASES.contains(&name.as_str())
        })
        .collect())
}

/// Aliases the shell defines for its own tooling, which users rarely want to
/// manage.
const SHELL_INTERNAL_ALIASES: &[&str] = &["run-help", "run-suite", "run-test", "which-command"];

fn run_shell_snippet(shell: Shell, snippet: &str, timeout: Duration) -> Result<String> {
    use std::io::Read;

    let mut child = Command::new(shell.as_str())
        .arg("-i")
        .arg("-c")
        .arg(snippet)
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::null())
        .spawn()
        .with_context(|| format!("spawning {}", shell.as_str()))?;

    // Drain stdout on a thread so a large alias list cannot fill the pipe
    // buffer and deadlock the child before it exits.
    let mut stdout = child.stdout.take();
    let reader = std::thread::spawn(move || {
        let mut buf = String::new();
        if let Some(s) = stdout.as_mut() {
            let _ = s.read_to_string(&mut buf);
        }
        buf
    });

    match child.wait_timeout(timeout)? {
        Some(_) => {}
        None => {
            let _ = child.kill();
            let _ = child.wait();
            bail!("{} timed out while listing aliases", shell.as_str());
        }
    }

    Ok(reader.join().unwrap_or_default())
}

/// Build importable entries from active definitions not already in the store,
/// tagging each with the given kind in the `imported` category.
pub fn importable_entries(
    active: &[(String, String)],
    kind: Kind,
    known: &dyn Fn(&str) -> bool,
) -> Vec<Entry> {
    active
        .iter()
        .filter(|(name, _)| !known(name))
        .map(|(name, command)| {
            let mut e = Entry::new(name, kind, command, "Imported from shell");
            e.category = "imported".into();
            e.tags = vec!["imported".into()];
            e
        })
        .collect()
}

/// Collect the active functions from an interactive shell process.
pub fn collect_active_functions(shell: Shell) -> Result<Vec<(String, String)>> {
    let snippet = match shell {
        Shell::Zsh => "functions",
        Shell::Bash => "declare -f",
    };
    let output = run_shell_snippet(shell, snippet, Duration::from_secs(10))?;
    Ok(parse_functions(&output)
        .into_iter()
        .filter(|(name, _)| is_importable_name(name))
        .collect())
}

/// Whether a discovered function name is a safe, importable trigger.
fn is_importable_name(name: &str) -> bool {
    !name.is_empty()
        && !name.starts_with('_')
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.'))
}

/// Parse `functions` / `declare -f` output into (name, body) pairs. The body is
/// the content between the outermost braces, matching how functions are stored.
pub fn parse_functions(text: &str) -> Vec<(String, String)> {
    let lines: Vec<&str> = text.lines().collect();
    let mut out = Vec::new();
    let mut i = 0;
    while i < lines.len() {
        let Some(name) = function_header(lines[i]) else {
            i += 1;
            continue;
        };

        let mut depth = 0i32;
        let mut seen_open = false;
        let mut body: Vec<String> = Vec::new();
        let mut j = i;
        while j < lines.len() {
            let line = lines[j];
            let opens = line.matches('{').count() as i32;
            let closes = line.matches('}').count() as i32;

            if !seen_open {
                if opens > 0 {
                    seen_open = true;
                    depth += opens - closes;
                    if depth <= 0 {
                        // Single-line function: `f () { body }`.
                        if let (Some(a), Some(b)) = (line.find('{'), line.rfind('}'))
                            && b > a
                        {
                            let inner = line[a + 1..b].trim();
                            if !inner.is_empty() {
                                body.push(inner.to_string());
                            }
                        }
                        out.push((name.clone(), body.join("\n")));
                        j += 1;
                        break;
                    }
                }
            } else {
                depth += opens - closes;
                if depth <= 0 {
                    out.push((name.clone(), body.join("\n")));
                    j += 1;
                    break;
                }
                body.push(line.to_string());
            }
            j += 1;
        }
        i = j.max(i + 1);
    }
    out
}

/// Detect a `name ()` function header line, returning the function name.
fn function_header(line: &str) -> Option<String> {
    let trimmed = line.trim();
    let paren = trimmed.find("()")?;
    let name = trimmed[..paren].trim();
    if !name.is_empty()
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-' | '.' | ':'))
    {
        Some(name.to_string())
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_alias_and_function() {
        let mut entries = vec![
            Entry::new("gitsw", Kind::Alias, "git switch", "switch"),
            Entry::new("kruby", Kind::Function, "echo hi\nkill -9 1", "kill ruby"),
        ];
        entries[1].kind = Kind::Function;
        let text = render(Shell::Zsh, &entries);
        assert!(text.contains("alias gitsw='git switch'"));
        assert!(text.contains("kruby() {\necho hi\nkill -9 1\n}"));
    }

    #[test]
    fn alias_single_quotes_are_escaped() {
        let e = Entry::new("say", Kind::Alias, "echo 'hi there'", "say hi");
        let text = render(Shell::Bash, std::slice::from_ref(&e));
        assert!(text.contains(r"alias say='echo '\''hi there'\'''"));
    }

    #[test]
    fn render_is_sorted_and_deterministic() {
        let entries = vec![
            Entry::new("b", Kind::Alias, "echo b", "b"),
            Entry::new("a", Kind::Alias, "echo a", "a"),
        ];
        let text = render(Shell::Zsh, &entries);
        let a = text.find("alias a=").unwrap();
        let b = text.find("alias b=").unwrap();
        assert!(a < b);
    }

    #[test]
    fn upsert_block_is_idempotent() {
        let block = rc_block(Path::new("/home/x/.config/cmd-man/shell/cmd-man.zsh"));
        let once = upsert_block("export PATH=/bin\n", &block);
        let twice = upsert_block(&once, &block);
        assert_eq!(once, twice);
        assert!(once.contains(BLOCK_START));
        assert!(once.contains("export PATH=/bin"));
    }

    #[test]
    fn upsert_block_recovers_from_missing_end_marker() {
        // A corrupted block (start marker, no end marker) must not accumulate
        // duplicate managed blocks.
        let block = rc_block(Path::new("/x.zsh"));
        let corrupted = format!("# top\n{BLOCK_START}\nsource /old\n");
        let fixed = upsert_block(&corrupted, &block);
        assert_eq!(fixed.matches(BLOCK_START).count(), 1);
        assert!(fixed.contains("# top"));
        // Re-applying stays stable.
        assert_eq!(upsert_block(&fixed, &block), fixed);
    }

    #[test]
    fn upsert_block_replaces_old_block() {
        let old = rc_block(Path::new("/old/path.zsh"));
        let new = rc_block(Path::new("/new/path.zsh"));
        let with_old = upsert_block("# top\n", &old);
        let with_new = upsert_block(&with_old, &new);
        assert!(with_new.contains("/new/path.zsh"));
        assert!(!with_new.contains("/old/path.zsh"));
        // Only one managed block remains.
        assert_eq!(with_new.matches(BLOCK_START).count(), 1);
    }

    #[test]
    fn parse_aliases_handles_quotes_and_prefix() {
        let text = "alias gitsw='git switch'\nll='ls -la'\nsay=\"echo hi\"\n# comment\nbad line\n";
        let parsed = parse_aliases(text);
        assert!(parsed.contains(&("gitsw".to_string(), "git switch".to_string())));
        assert!(parsed.contains(&("ll".to_string(), "ls -la".to_string())));
        assert!(parsed.contains(&("say".to_string(), "echo hi".to_string())));
    }

    #[test]
    fn importable_filters_known() {
        let active = vec![
            ("gitsw".to_string(), "git switch".to_string()),
            ("ll".to_string(), "ls -la".to_string()),
        ];
        let known = |n: &str| n == "gitsw";
        let out = importable_entries(&active, Kind::Alias, &known);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].name, "ll");
        assert_eq!(out[0].kind, Kind::Alias);
        assert_eq!(out[0].category, "imported");
    }

    #[test]
    fn parses_zsh_style_functions() {
        let text = "kruby () {\n\techo hi\n\tkill -9 1\n}\ngreet () {\n\techo hello\n}\n";
        let parsed = parse_functions(text);
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[0].0, "kruby");
        assert!(parsed[0].1.contains("echo hi"));
        assert!(parsed[0].1.contains("kill -9 1"));
        assert_eq!(parsed[1].0, "greet");
    }

    #[test]
    fn parses_bash_style_functions_with_brace_on_own_line() {
        let text = "myfn () \n{ \n    echo one;\n    echo two\n}\n";
        let parsed = parse_functions(text);
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0].0, "myfn");
        assert!(parsed[0].1.contains("echo one;"));
        assert!(parsed[0].1.contains("echo two"));
    }

    #[test]
    fn parses_single_line_function() {
        let parsed = parse_functions("hi () { echo hi }\n");
        assert_eq!(parsed.len(), 1);
        assert_eq!(parsed[0].0, "hi");
        assert_eq!(parsed[0].1, "echo hi");
    }

    #[test]
    fn importable_name_filters_internal_and_invalid() {
        assert!(is_importable_name("gitsw"));
        assert!(!is_importable_name("_private"));
        assert!(!is_importable_name("has:colon"));
        assert!(!is_importable_name(""));
    }
}
